spring:
  r2dbc:
    url: r2dbc:pool:h2:mem:///pay_db?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MV_STORE=FALSE;user=sa;password=
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG


security:
  password: renuevo


